### ISSUE TITLE
失礼します！DiscordBotを作成してでこれを参考にしたのですが…

### ISSUE THREAD

**Issue by AlphaIru** [Nemy-z2z/readBot#4]
失礼します！DiscordBotを作成してでこれをベースにしたのですがNemyさんのクレジッドを使ってライセンス公開していいでしょうか？

**Comment by Nemy-z2z** [comment]
返事遅れてすみません。申し訳ないんですが、このコードは私も別の方のコードを参考にしたりしてて権利とかややこしいので一律なしでお願いします。。。

**Comment by AlphaIru** [comment]
あちゃ…、そうですか…、自分、作ったのは良いんですけど初心者でGithubのやり方が分からずじまいなので…、どうしようかと…

失礼しました！

っていうか…、Qiitaの方から入りまして、自分でアレンジをした感じです。で、それがかなりオーバースペックなほど機能が満載になったので新Repo作って、Yomiage_Engineとして出そうとしてるんですけど…、いくつかのがNemy_ZZさんのを参考にしてるので、どうしたら良いのかわからないです…

（あの…、できるならどうしてほしいのか具体的にお願いします…、自分、外国人で日本語苦手なので、汗）
